### ISSUE TITLE
Add modulepath to puppet apply

### ISSUE THREAD

**Issue by jpsheffield** [WhatsARanjit/puppet-puppeteer#4]
Would it be possible to add a modulepath parameter to the puppet apply task? I've tried to do it but I'm new to ruby and can't see how. The default modulepath doesn't seem to get used.

**Comment by WhatsARanjit** [comment]
@jpsheffield Give this a try.

https://github.com/WhatsARanjit/puppet-puppeteer/pull/6

Will merge into next release.
